[package]
name = "polytrack-codes"
version = "0.4.0-pre.3"
edition = "2024"
license = "MIT"
description = "Collection of utilities to work with PolyTrack's track codes"
repository = "https://codeberg.org/polytools/polycodes"
readme = "README.md"

[dependencies]
base64 = "0.22.1"
facet = "0.46.5"
facet-json = "0.46.1"
flate2 = { version = "1.1.9", default-features = false, features = ["zlib"] }
num_enum = "0.7.5"
sha256 = "1.6.0"
type-equalities = "0.3.1"

[patch.crates-io]
flate2 = { git = "https://codeberg.org/polytools/flate2-rs_polytrack", branch = "main" }
